# A catppuccin RC for joplin. In beta, specs may change. 
app_name: joplin 
binary_name: joplin 
installation:
  location: 
    macos: ~/.config/joplin-desktop/
    linux: ~/.config/joplin-desktop/
    windows: "%appdata%/Joplin"
  flavours:
    latte: 
      default: 
        - src/latte/userchrome.css
        - src/latte/userstyle.css
    frappe: 
      default: 
        - src/frappe/userchrome.css
        - src/frappe/userstyle.css
    macchiato: 
      default:
        - src/macchiato/userchrome.css
        - src/macchiato/userstyle.css
    mocha: 
      default:
        - src/mocha/userchrome.css
        - src/mocha/userstyle.css
  to: .
  one_flavour: true


